name: foodscan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  barcode_scan2: ^4.3.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.1
  flutter_secure_storage: ^9.2.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_generative_ai: ^0.4.0
  intl: ^0.19.0
  openfoodfacts: ^3.9.0
  provider: ^6.1.2
  share: ^2.0.4
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/onboard/
    - assets/html/
